version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels: ["deps", "pip", "dependabot"]
    commit-message:
      prefix: "deps(pip)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    labels: ["deps", "gha", "dependabot"]
    commit-message:
      prefix: "deps(gha)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    labels: ["deps", "docker", "dependabot"]
    commit-message:
      prefix: "deps(docker)"
