changelog:
  categories:
    - title: Features
      labels: [feature]
    - title: Fixes
      labels: [bug]
    - title: Security
      labels: [security]
    - title: Maintenance
      labels: [chore, deps]
