[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-todo"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
]
