name: Canary Health

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch: {}

permissions:
  contents: read

env:
  TIMEOUT: "15"

jobs:
  canary:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.APP_URL }}
    steps:
      - name: Validate inputs
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "APP_URL secret is required"; exit 1
          fi
          echo "Base URL: $BASE_URL"

      - name: Health check
        run: |
          set -euo pipefail
          BASE="${BASE_URL%/}"
          code=$(curl -sS -m "$TIMEOUT" -L -o /dev/null -w "%{http_code}" "$BASE/health")
          echo "Health HTTP $code"
          test "$code" = "200"
