name: CI (PR) + Deploy (main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REGISTRY:   ${{ secrets.ECR_REGISTRY }}
  IMAGE_URI:      ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}
  APP_RUNNER_SERVICE_ARN: ${{ secrets.APP_RUNNER_SERVICE_ARN }}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Run pytest
        run: |
          if [ -f pyproject.toml ] || [ -f pytest.ini ] || [ -d tests ]; then
            pytest -q
          else
            echo "No tests configured, skipping."
          fi

  deploy:
    name: Build → Push → Update App Runner
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Docker image (latest + SHA)
        run: |
          set -euo pipefail
          SHORT_SHA="${GITHUB_SHA::7}"
          docker build -t "$IMAGE_URI:latest" -t "$IMAGE_URI:$SHORT_SHA" .
          docker push "$IMAGE_URI:$SHORT_SHA"
          docker push "$IMAGE_URI:latest"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Update App Runner service to latest image
        run: |
          aws apprunner update-service \
            --service-arn "$APP_RUNNER_SERVICE_ARN" \
            --source-configuration "ImageRepository={ImageIdentifier=${IMAGE_URI}:latest,ImageRepositoryType=ECR,ImageConfiguration={Port=8000,RuntimeEnvironmentVariables=[{Name=UVICORN_WORKERS,Value=2}]}}" \
            --region "$AWS_REGION"
