name: Release (SBOM attached)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: rel-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build image (local only)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: fastapi-todo:${{ env.IMAGE_TAG }}

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0.17.9
        with:
          image: fastapi-todo:${{ env.IMAGE_TAG }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Create GitHub Release (attach SBOM)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.spdx.json
