name: SBOM
on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: fastapi-todo:sbom-${{ github.sha }}
      - name: Generate SPDX SBOM (Syft)
        uses: anchore/sbom-action@v0.17.9
        with:
          image: fastapi-todo:sbom-${{ github.sha }}
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom.spdx.json
          path: sbom.spdx.json
